apiVersion: apps/v1
kind: Deployment

metadata:
  name: sistema-mecanica
  namespace: gashu-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: sistema-mecanica

  template:
    metadata:
      labels:
        app: sistema-mecanica

    spec:
      containers:
        - name: sistema-mecanica

          #image: meu-registry/sistema-mecanica:1.0.0
          image: kenjigashu/sistema-mecanica:main

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: sistema-mecanica-config

            - secretRef:
                name: sistema-mecanica-secret

          resources:
            requests:
              cpu: 200m
              memory: 256Mi

            limits:
              cpu: 500m
              memory: 512Mi

          livenessProbe:
            httpGet:
              path: /health
              port: 8080

            initialDelaySeconds: 20
            periodSeconds: 15

          readinessProbe:
            httpGet:
              path: /health
              port: 8080

            initialDelaySeconds: 10
            periodSeconds: 10
