apiVersion: v1
kind: Secret
metadata:
  name: sistema-mecanica-secret
  namespace: gashu-app

type: Opaque

stringData:
  POSTGRES_PASSWORD: "mypassword"
  ConnectionStrings__Default: "Host=db;Port=5432;Database=mydb;Username=myuser;Password=mypassword"
  FIAP_POS_APP_PASSWORD: "iotjahrsjmogmdyc"
  FIAP_POS_SALT: "pesomorto"
  FIAP_POS_SECRET: "minha_chave_super_secreta_com_32_chars!!"
