apiVersion: v1
kind: Service
metadata:
  name: sistema-mecanica-externo
  namespace: gashu-app
spec:
  type: NodePort

  selector:
    app: sistema-mecanica

  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
