apiVersion: v1
kind: Service

metadata:
  name: sistema-mecanica-service
  namespace: gashu-app

spec:
  selector:
    app: sistema-mecanica

  ports:
    - port: 80
      targetPort: 8080

  type: ClusterIP
